/*
CREATED BY SAMIRA ALVES LUCIO DIAS
DATE: 19/06/2020
GOAL: REPORT DEVELOPED TO RETURN ITEMS 
THAT WERE MISSED ON THE COUNT OF AN INVENTORY, 
INDEPENDENT OF HUMAN FILL TO GENERATE IT
*/

SELECT PRODUTO.CD_PRODUTO
      ,PRODUTO.DS_PRODUTO
      ,EST_PROQT_ESTOQUE_ATUAL
      ,PRODUTO.CD_CLASSE
FROM PRODUTO PRODUTO
INNER JOIN EST_PRO EST_PRO
ON PRODUTO.CD_PRODUTO = EST_PRO.CD_PRODUTO 
WHERE EST_PRO.CD_ESTOQUE = #ESTOQUE# --CODIGO ESTOQUE - EST_PRO
AND PRODUTO.CD_ESPECIE IN (#ESPECIE#) -- ESPECIE - PRODUTO
AND PRODUTO.CD_CLASSE = #CD_CLASSE# --CLASSE - PRODUTO
AND PRODUTO.SN_MESTRE ='N' -- PRODUTO
AND EST_PRO.QT_ESTOQUE_ATUAL <> 0 -- EST_PRO
AND EST_PRO.CD_PRODUTO NOT IN  -- EST_PRO
    (SELECT CD_PRODUTO FROM ITEM_CONTAGEM_USUARIO -- TABELA DIFERENTE
     WHERE CD_CONTAGEM IN (#CONTAGEM_EST#))
AND EST_PRO.CD_PRODUTO NOT IN --EST_PRO
    (SELECT CD_PRODUTO FROM ITCONTAGEM --TABELA DIFERENTE
     WHERE CD_CONTAGEM IN (#CONTAGEM_EST#))
;





-- 


