/*
CREATED BY SAMIRA ALVES LUCIO DIAS
DATE: 19/06/2020
GOAL: VALUE LIST DEVELOPED TO FILL THE SPECIES FROM A STOCK TO MAKE AUTOMATIC SEARCH
*/

-- LISTA E VALORES ESPÉCIE
/* in this case it's not necessary the use concat because on the value list it's able
to adjust*/
SELECT DISTINCT PRODUTO.CD_ESPECIE, ESPECIE.DS_ESPECIE 
FROM PRODUTO PRODUTO
INNER JOIN ESPECIE ESPECIE
ON PRODUTO.CD_ESPECIE = ESPECIE.CD_ESPECIE
ORDER BY PRODUTO.CD_ESPECIE;
