/*
CREATED BY SAMIRA ALVES LUCIO DIAS
DATE: 19/06/2020
GOAL: VALUE LIST DEVELOPED TO FILL THE SPECIES FROM A STOCK TO MAKE AUTOMATIC SEARCH
*/

-- LISTA E VALORES ESPÉCIE
SELECT  * FROM
(SELECT DISTINCT CONCAT (CONCAT(PRODUTO.CD_ESPECIE, ' - '), ESPECIE.DS_ESPECIE) AS ESPÉCIES
FROM PRODUTO PRODUTO
INNER JOIN ESPECIE ESPECIE
ON PRODUTO.CD_ESPECIE = ESPECIE.CD_ESPECIE) TESTE
ORDER BY TESTE
;
