/*
CREATED BY SAMIRA ALVES LUCIO DIAS
DATE: 19/06/2020
GOAL: VALUE LIST DEVELOPED TO FILL THE STOCK TO MAKE AUTOMATIC SEARCH
*/

-- LISTA DE VALORES ESTOQUE
SELECT DISTINCT EST_PRO.cd_estoque ||' - '||ESTOQUE.DS_ESTOQUE "ESTOQUES"
FROM EST_PRO EST_PRO
INNER JOIN ESTOQUE ESTOQUE
ON ESTOQUE.CD_ESTOQUE = EST_PRO.CD_ESTOQUE
ORDER BY EST_PRO.cd_estoque ||' - '||ESTOQUE.DS_ESTOQUE;

---- Consulta busca campo
select * from all_tab_columns
where upper (column_name) like 'DS_ESPECIE';
